### ISSUE TITLE
[Heads up] Build broken this morning

### ISSUE THREAD

**Issue by phidebian** [ksh93/ksh#631]
Hi BE gurus,
This morning I can't build, and I admit I am fairly ignorant of the BE process, religiously aplly the same command from my hist file to build.

I am running ubuntu 22.04 LTS with almost current tool chain. More detail on this if relevant on requets, I got thefeeling it should be a minor glitch pushed yesterday. 

I got this
````
iffe: test: do wctrans/towctrans work ... yes
+ cc -m64 -O0 -g3 -I. -I/d1/ksh-latest/src/cmd/ksh93 -Iinclude -I/d1/ksh-latest/src/cmd/ksh93/include -I/d1/ksh-latest/arch/linux.i386-64/include/ast '-D_API_ast=20100309' '-DERROR_CONTEXT_T=Error_context_t' -c /d1/ksh-latest/src/cmd/ksh93/bltins/hist.c
In file included from /d1/ksh-latest/src/cmd/ksh93/bltins/hist.c:29:
/d1/ksh-latest/src/cmd/ksh93/include/edit.h:30:17: fatal error: FEATURE/cmds: No such file or directory
   30 | #include        "FEATURE/cmds"
      |                 ^~~~~~~~~~~~~~
compilation terminated.
mamake [cmd/ksh93]: *** exit code 1 making hist.o

````

**Comment by posguy99** [comment]
Broken by aa978a85.  Revert it and the build succeeds.

**Comment by phidebian** [comment]
I dunno how ot `revert` it, the only thing I know is to checkout something earlier like the one before.

````
$ git ls | head -5
5d3479b4 actually compile out multiline support where disabled (re: 0fef770c) [Martijn Dekker] (origin/1.0)
aa978a85 actually compile out multiline support where disabled (re: 79a908f4) [Martijn Dekker] (HEAD -> dev, origin/dev, origin/HEAD)
0fef770c tput testing adjustments (#630) [Martijn Dekker]
79a908f4 tput testing adjustments (#630) [GitHub]
d01798f5 build system tweaks: do not unnecessarily re-run iffe tests [Martijn Dekker]

$ git co -b 0fef770c
Switched to a new branch '0fef770c'

$ rm -rf arch/
$ ./bin/package make CCFLAGS='-Dregister= -m64 -O0 -g3' LDFLAGS='-m64 -g3'
...
iffe: test: do wctrans/towctrans work ... yes
+ cc '-Dregister=' -m64 -O0 -g3 -I. -I/d1/ksh-latest/src/cmd/ksh93 -Iinclude -I/d1/ksh-latest/src/cmd/ksh93/include -I/d1/ksh-latest/arch/linux.i386-64/include/ast '-D_API_ast=20100309' '-DERROR_CONTEXT_T=Error_context_t' -c /d1/ksh-latest/src/cmd/ksh93/bltins/hist.c
In file included from /d1/ksh-latest/src/cmd/ksh93/bltins/hist.c:29:
/d1/ksh-latest/src/cmd/ksh93/include/edit.h:30:17: fatal error: FEATURE/cmds: No such file or directory
   30 | #include        "FEATURE/cmds"
      |                 ^~~~~~~~~~~~~~
compilation terminated.
...

````

I start to fear something specific to my system, may be an unfortunate update, but I doubt.
A good thing though, my old BE (not pulled) still work, so this one cross out my system, yet I am still lost in the void at the moment.

**Comment by posguy99** [comment]
Check out 79a908f4 and the build will succeed.

**Comment by posguy99** [comment]
I'm certainly not the person to ask how the build system works, that `cmds` file is getting created in `src/cmd/ksh93/features` though.

**Comment by phidebian** [comment]
Well still fail, I re cloned all fresh, did the co right away

````
$ git clone  https://github.com/ksh93/ksh ksh-lt
$ cd ksh-lt
$ co -b 79a908f
Switched to a new branch '79a908f'
$ rm -rf arch/
$ ./bin/package make CCFLAGS='-m64 -O0 -g3' LDFLAGS='-m64 -g3'
iffe: test: do wctrans/towctrans work ... yes
+ cc -m64 -O0 -g3 -I. -I/d1/ksh/src/cmd/ksh93 -Iinclude -I/d1/ksh/src/cmd/ksh93/include -I/d1/ksh/arch/linux.i386-64/include/ast '-D_API_ast=20100309' '-DERROR_CONTEXT_T=Error_context_t' -c /d1/ksh/src/cmd/ksh93/bltins/hist.c
In file included from /d1/ksh/src/cmd/ksh93/bltins/hist.c:29:
/d1/ksh/src/cmd/ksh93/include/edit.h:30:17: fatal error: FEATURE/cmds: No such file or directory
   30 | #include        "FEATURE/cmds"
      |                 ^~~~~~~~~~~~~~
compilation terminated.
````

Before breaking the whole thing I prefere to wait I guess I am entering the GIT grey zone :)

EDIT: Pilot error here, I reused my  history and did `git co -b 79a908f` and landed in a 'new' branch from dev so still failing, when doing the proper `git checkout 79a908f` it build again as said @posguy99 . 

First time I got trapped with an unoticed tiny `-b`, scarred the shit outta me.

So I got my receipe back, the BE problem from pristine latest ksh exist on my s390x as well, so I guess this is a glitch...

I resume working one step back....

**Comment by pghvlaans** [comment]
I don't know if this is 100% the right way to do this, but this patch should get it building again.

```
diff --git a/src/cmd/ksh93/Mamfile b/src/cmd/ksh93/Mamfile
index d1a08c56..9b71b7bb 100644
--- a/src/cmd/ksh93/Mamfile
+++ b/src/cmd/ksh93/Mamfile
@@ -195,6 +195,11 @@ make install
                                        done ${PACKAGE_ast_INCLUDE}/stk.h
                                        make include/history.h implicit
                                                prev ${PACKAGE_ast_INCLUDE}/ast.h implicit
+                                               make FEATURE/cmds implicit
+                                                       make features/cmds
+                                                       done features/cmds
+                                                       exec - iffe ${IFFEFLAGS} -v -c "${CC} ${mam_cc_FLAGS} ${CCFLAGS} ${LDFLAGS}" ref ${mam_cc_L+-L.} ${mam_cc_L+-L${INSTALLROOT}/lib} -I${PACKAGE_ast_INCLUDE} -I${INSTALLROOT}/include ${mam_libdll} ${mam_libcmd} ${mam_libast} ${mam_libm} ${mam_libnsl} : run features/cmds
+                                               done FEATURE/cmds generated
                                        done include/history.h
                                        make ${PACKAGE_ast_INCLUDE}/cmd.h implicit
                                                make ${PACKAGE_ast_INCLUDE}/dlldefs.h implicit
```

EDIT: formatting

**Comment by pghvlaans** [comment]
Indeed, it was not. Still worked, but I meant to put those lines in with `edit.h`.

```
diff --git a/src/cmd/ksh93/Mamfile b/src/cmd/ksh93/Mamfile
index d1a08c56..41ca8c29 100644
--- a/src/cmd/ksh93/Mamfile
+++ b/src/cmd/ksh93/Mamfile
@@ -366,6 +366,11 @@ make install
                                                        done FEATURE/ttys generated
                                                done include/terminal.h
                                                prev ${PACKAGE_ast_INCLUDE}/sig.h implicit
+                                               make FEATURE/cmds implicit
+                                                       make features/cmds
+                                                       done features/cmds
+                                                       exec - iffe ${IFFEFLAGS} -v -c "${CC} ${mam_cc_FLAGS} ${CCFLAGS} ${LDFLAGS}" ref ${mam_cc_L+-L.} ${mam_cc_L+-L${INSTALLROOT}/lib} -I${PACKAGE_ast_INCLUDE} -I${INSTALLROOT}/include ${mam_libdll} ${mam_libcmd} ${mam_libast} ${mam_libm} ${mam_libnsl} : run features/cmds
+                                               done FEATURE/cmds generated
                                                make FEATURE/locale implicit
                                                        make features/locale
                                                        done features/locale
```

**Comment by McDutchie** [comment]
@pghvlaans wrote:
> Indeed, it was not. Still worked, but I meant to put those lines in with `edit.h`.

Yes, that is the correct fix, and indeed that is what I had locally. Clearly, I messed something up in actually committing all the changes before going to sleep. My bad; apologies everyone.

**Comment by McDutchie** [comment]
By the way, in case anyone hadn't noticed, documentation for mamake and the Mamfiles is now in [src/cmd/INIT/README-mamake.md](/ksh93/ksh/blob/dev/src/cmd/INIT/README-mamake.md).

**Comment by phidebian** [comment]
@McDutchie Didn't even knew their existence (mamake and the Mamfiles) but now you said it, I gotta read it, just clicked on it an looks good...
Just curious is their an IRC somewhere for this kind of popup discusssion ?

**Comment by McDutchie** [comment]
@phidebian There's #ksh on irc.libera.chat but that's for all ksh variants, not just ours. I seem to recall it was started by Thorsten Glaser who is the maintainer of mksh (the best current pdksh derivative).

**Comment by phidebian** [comment]
Ok thanx.
