### PR TITLE
Fix build under LLVM15

### PR DESCRIPTION
**Pull request by cschuber**
-Wint-conversion is now default with LLVM15. Fix the following -Wint-conversion error.

error: incompatible integer to pointer conversion passing 'uint64_t' (aka 'unsigned long') to parameter of type 'void *' [-Wint-conversion]
                return _aso_casptr((void**)p, o, n);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
./FEATURE/aso:19:66: note: expanded from macro '_aso_casptr'
                                                                      ^~~~~~~~~~~
/wrkdirs/usr/ports/shells/ksh-devel/work/ksh-9bec2b78/src/lib/libast/aso/aso.c:839:10: error: incompatible integer to pointer conversion passing 'uint64_t' (aka 'unsigned long') to parameter of type 'void *' [-Wint-conversion]
                return _aso_casptr((void**)p, o, n);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
./FEATURE/aso:19:78: note: expanded from macro '_aso_casptr'
                                                                                  ^~~~~~~~~~~
2 errors generated.

### CODE REVIEW

**Comment by JohnoKing** [comment]
I'll note that I just encountered this build error while trying to build using clang version 15.0.7 on Linux. I had to apply the fix from here manually to get ksh to build, since it's still not upstreamed.

**Comment by McDutchie** [comment]
I'll just merge this then, since it's now confirmed. Thanks for the PR!

**Comment by cschuber** [comment]
Thanks.
