### ISSUE TITLE
Build currently fails on Cygwin

### ISSUE THREAD

**Issue by JohnoKing** [ksh93/ksh#423]
The build currently fails on Cygwin (Windows 11 x86_64) with an error in setlocale.c. This is a regression introduced in commit a38e8047786b1576d1ef979a9bbafbcd1c343a74.

The errors in setlocale are shown below:
```
+ cc -D_BLD_ast -Os -I. -I/home/ksh/src/lib/libast -Icomp -I/home/ksh/src/lib/libast/comp -Iport -I/home/ksh/src/lib/libast/port -Iinclude -I/home/ksh/src/lib/libast/include -Istd -I/home/ksh/src/lib/libast/std -I/home/ksh/arch/cygwin.i386-64/include -D_PACKAGE_ast -c /home/ksh/src/lib/libast/comp/setlocale.c
/home/ksh/src/lib/libast/comp/setlocale.c: In function 'set_ctype':
/home/ksh/src/lib/libast/comp/setlocale.c:2255:83: error: 'wcwidth' undeclared (first use in this function); did you mean 'mbwidth'?
 2255 |                 if ((locales[cp->internal]->flags & LC_local) || !(ast.mb_width = wcwidth))
      |                                                                                   ^~~~~~~
      |                                                                                   mbwidth
/home/ksh/src/lib/libast/comp/setlocale.c:2255:83: note: each undeclared identifier is reported only once for each function it appears in
/home/ksh/src/lib/libast/comp/setlocale.c: In function 'single':
/home/ksh/src/lib/libast/comp/setlocale.c:2541:151: error: 'wcwidth' undeclared (first use in this function); did you mean 'mbwidth'?
 2541 |                                 , ast.mb_width == debug_wcwidth ? " debug_wcwidth" : ast.mb_width == utf8_wcwidth ? " utf8_wcwidth" : ast.mb_width == wcwidth ? " wcwidth" : ast.mb_width == default_wcwidth ? " default_wcwidth" : ""
      |                                                                                                                                                       ^~~~~~~
      |                                                                                                                                                       mbwidth
mamake [lib/libast]: *** exit code 1 making setlocale.o
```

Full build log: [ksh-log.txt](https://github.com/ksh93/ksh/files/7856296/ksh-log.txt)

**Comment by McDutchie** [comment]
Odd. I can't reproduce this. It's working for me on Cygwin on 32-bit Windows 7 (although vvvvveeeeeeerrrrrry slllloooowwwwwllllyyyyyyy as usual).

Maybe on newer Cygwin we need to use `_GNU_SOURCE`. That one is no longer part of the shotgun fallback as of that commit.

On my Cygwin, `/usr/include/features.h` documents:

```
/* Various options should be defined here, but the framework to do this
   is not laid down so far.  Especially notable are the following defines,
   which can be used by the application to switch on or off various
   datatypes and function prototypes:

     _BSD_SOURCE   to include pure BSD functions which are not defined
		   under POSIX.

     _POSIX_SOURCE if the application requests a POSIX compatible system.

     _XOPEN_SOURCE if X/Open functions and datatypes are requested.  This
		   option includes _POSIX_SOURCE.

     _GNU_SOURCE   to turn on GNU extensions which might collide with defines
		   used in application or library headers.  This option
		   includes _BSD_SOURCE, _XOPEN_SOURCE and _POSIX_SOURCE.
*/
```

Did anything about that change in your version?

**Comment by McDutchie** [comment]
Does this patch fix it on your end?
```diff
--- a/src/lib/libast/features/standards
+++ b/src/lib/libast/features/standards
@@ -105,7 +105,7 @@ elif tst note{ SunOS (Solaris, illumos) }end compile{
 		#define	_XOPEN_SOURCE	9900
 		#undef _POSIX_C_SOURCE
 	}
-elif tst note{ GNU (glibc) }end compile{
+elif tst note{ GNU (glibc) or Cygwin }end compile{
 		/*
 		 * GNU (GNU's Not UNIX). From feature_test_macros(7) on a GNU/Linux system with glibc 2.32:
 		 *
@@ -126,8 +126,8 @@ elif tst note{ GNU (glibc) }end compile{
 		#include <unistd.h>
 		#include <features.h>
 		#include <sys/types.h>
-		#if !__GLIBC__
-		#error not GNU
+		#if !__GLIBC__ && !__CYGWIN__
+		#error not GNU or Cygwin
 		#endif
 		int _do_these_compile_ = _POSIX_PATH_MAX & _SC_PAGESIZE;
 		#if _typ_u_long
```

**Comment by JohnoKing** [comment]
That patch does fix the issue. I created a similar patch about half an hour ago, but I couldn't confirm the fix until Cygwin finished compiling. Here's a version with some improvements:
```diff
diff --git a/src/lib/libast/features/standards b/src/lib/libast/features/standards
index 1a6a392e..0a102da2 100644
--- a/src/lib/libast/features/standards
+++ b/src/lib/libast/features/standards
@@ -105,7 +105,7 @@ elif tst note{ SunOS (Solaris, illumos) }end compile{
 		#define	_XOPEN_SOURCE	9900
 		#undef _POSIX_C_SOURCE
 	}
-elif tst note{ GNU (glibc) }end compile{
+elif tst note{ GNU (glibc) or Cygwin }end compile{
 		/*
 		 * GNU (GNU's Not UNIX). From feature_test_macros(7) on a GNU/Linux system with glibc 2.32:
 		 *
@@ -120,14 +120,16 @@ elif tst note{ GNU (glibc) }end compile{
 		 *          Since glibc 2.19, defining _GNU_SOURCE also has the effect of implicitly defin‐
 		 *          ing _DEFAULT_SOURCE.  In glibc versions before 2.20, defining _GNU_SOURCE  also
 		 *          had the effect of implicitly defining _BSD_SOURCE and _SVID_SOURCE.
+		 *
+		 * Additionally, on Cygwin we must use _GNU_SOURCE to enable all features required by libast.
 		 */
 		#define _GNU_SOURCE	1
 		#include <limits.h>
 		#include <unistd.h>
 		#include <features.h>
 		#include <sys/types.h>
-		#if !__GLIBC__
-		#error not GNU
+		#if !__GLIBC__ && !__CYGWIN__
+		#error not GNU or Cygwin
 		#endif
 		int _do_these_compile_ = _POSIX_PATH_MAX & _SC_PAGESIZE;
 		#if _typ_u_long

```

**Comment by McDutchie** [comment]
Thanks. I'll also add wcwidth as an extra heuristic to the BSD, SunOS, Darwin and GNU/Cygwin tests. (Since it's specified as an optional (X/Open) feature, it should not be tested for in the generic fallbacks.)

**Comment by JohnoKing** [comment]
Fixed as of commit 8386afcddfe8deb5daced94cb885222c2ce4e967.
